# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BamShell
brief-intro: From God to Sysadmin
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clebam.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: clebam
reddit_username: clebam
#facebook_username: gaohaoyang.water
github_username: clebam
#email: gaohaoyang126@126.com
#weibo_username: 3115521wh
#zhihu_username: gaohaoyang
#linkedIn_username: gaohaoyang
#dribbble_username:
description_footer: Made by Clebam -

# comments
disqus_shortname: bamshell

# statistic analysis
google_analytics_id: UA-113129144-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "<!--End_Preview-->"

# paginate
paginate: 6

# Technical
description: From God to Sysadmin
github: [metadata]

# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate